# Generated by Django 4.0.2 on 2022-02-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="polygon",
            old_name="points",
            new_name="coordinates",
        ),
    ]
